#!/bin/sh
### BEGIN INIT INFO
# Provides:             aprx
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    APRS Digipeater Daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/aprx
NAME=aprx
DESC="APRS Digipeater Daemon"
PIDFILE=/var/run/aprx.pid

set -e

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon -S -p $PIDFILE -x "$DAEMON"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
    start-stop-daemon -S -p $PIDFILE -x "$DAEMON"
    echo "$NAME."
;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
